package com.dic.app.enums;

import com.ric.cmn.excp.WrongParam;
import lombok.Getter;

import java.util.Arrays;
import java.util.List;

// статусы ответа на запрос по задолженности в ГИС
@Getter
public enum DebtSubRequestResponseStatuses {
    NOT_SENT(0, "NotSent"), // не отправлено
    SENT(1, "Sent"), // отправлено
    AUTO_GENERATED(2, "AutoGenerated"); // ???

    private final int id;
    private final String name;

    DebtSubRequestResponseStatuses(int id, String name) {
        this.id=id;
        this.name = name;
    }

    public static DebtSubRequestResponseStatuses getByName(String name) throws WrongParam {
        DebtSubRequestResponseStatuses[] list = DebtSubRequestResponseStatuses.values();
        for (DebtSubRequestResponseStatuses status : list) {
            if (status.getName().equals(name))
                return status;
        }
        throw new WrongParam("Не найден DebtSubRequestStatuses.name = "+name);
    }

}
